Update RunId code

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -148,8 +148,12 @@ jobs:
         id: trigger_run
         run: |
           RESPONSE=$(curl -X POST -H "Authorization: Bearer ${{ secrets.PORT_API_TOKEN }}" https://api.getport.io/v1/runs -d '{"job":"your-job-details"}')
-          echo "Response from Port API: $RESPONSE"  # Log the response for debugging
+          echo "Response from Port API: $RESPONSE"
           runId=$(echo $RESPONSE | jq -r '.runId')
+          if [ -z "$runId" ] || [ "$runId" == "null" ]; then
+            echo "Error: runId is null or empty"
+            exit 1
+          fi
           echo "runId=$runId" >> $GITHUB_ENV
 
           
